[tox]
min_version = 4.0
requires =
    tox>=4
    tox-uv>=1.36,<2
env_list = py{310, 311, 312, 313, 314}, lint, type
isolated_build = true

[testenv]
runner = uv-venv-lock-runner
dependency_groups = test
commands = pytest tests

[testenv:lint]
runner = uv-venv-lock-runner
dependency_groups = lint
commands = flake8 src/

[testenv:type]
runner = uv-venv-lock-runner
dependency_groups = type
commands = mypy src/

[flake8]
max-line-length = 100
include = "/src/landmarker"
ignore=E203, W503
